FROM golang:1.24-alpine

WORKDIR app/

COPY go.mod go.sum ./

RUN go mod download

COPY utils/ ./utils/
COPY grpc/ ./grpc/ 
COPY proto/ ./proto/ 

RUN cd grpc && go build -o /grpc main.go

EXPOSE 8081

CMD ["/grpc"]