services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  # rpc-server:
  #   container_name: rpc-server
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.rpc
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - rabbitmq
  #     - api
  api:
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - rabbitmq
      - nginx
  
  # worker:
  #   container_name: worker
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.worker
  #   depends_on:
  #     - rabbitmq
  

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  rabbitmq-data:
